/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'doc',
      id: 'documentation',
      label: 'Introduction',
    },
    {
      type: 'link',
      label: 'Release Information',
      href: '/release-information'
    },
    {
      type: 'link',
      label: 'Getting Started Tutorials',
      href: '/tutorials'
    },
// PAULA START OF MAIN TOC - INSTALL AND UPGRADE
    {
      type: 'category',
      label: 'Install and Upgrade',
    //  link: {type: 'doc', id: 'install-and-upgrade'},
      items: [
        {
          type: 'category',
          label: 'Install Requirements',
          //link: {type: 'doc', id: 'install-requirements'},
          items: [
            {
              type: 'doc',
              id: 'which-erlang',
              label: 'Erlang Version Requirements',
            },
            {
              type: 'doc',
              id: 'signatures',
              label: 'Release Package Signatures',
            },
          ],
        },
        {
          type: 'category',
          label: 'Install Instructions',
          link: {type: 'doc', id: 'build'},
          items: [
            {
              type: 'doc',
              id: 'build-server',
              label: 'Building the Server',
            },
            {
              type: 'doc',
              id: 'github',
              label: 'Using Git and Github',
            },
          ],
        },
       {
         type: 'category',
         label: 'Operating Systems RabbitMQ can be Installed On',
         link: {type: 'doc', id: 'build'},
          items: [
            {
              type: 'category',
              label: 'Linux/Unix',
             link: {type: 'doc', id: 'build'},
              items: [
                  {
                  type: 'doc',
                  id: 'install-debian',
                  label: 'Debian and Ubuntu',
                  },
                 {
                  type: 'doc',
                  id: 'install-rpm',
                  label: 'RedHat',
                 },
                 {
                  type: 'doc',
                  id: 'install-generic-unix',
                  label: 'Generic Unix: Linux, MacOS, and BSD systems',
                 },
              ],
            },
           ],
         },
         {
          type: 'category',
          label: 'Upgrade',
          link: {type: 'doc', id: 'upgrade'},
          items: [
            {
              type: 'doc',
              id: 'blue-green-upgrade',
              label: ' Upgrading RabbitMQ Using Blue-Green Deployment Strategy',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'How to Use RabbitMQ',
      items: [
        {
          type: 'doc',
          id: 'feature-flags',
          label: 'Turning Features On and Off',
        },
        {
          type: 'doc',
          id: 'reliability',
          label: 'Reliable Delivery of Messages and Data Safety',
        },
    
      {
        type: 'category',
        label: 'Consuming Messages',
        link: {type: 'doc', id: 'admin-guide'},
        items: [
          {
            type: 'doc',
            id: 'consumers',
            label: 'Describing Consumers',
          },
          {
            type: 'doc',
            id: 'consumer-cancel',
            label: 'Consumer Cancellation Notification',
          },
          {
            type: 'doc',
            id: 'consumer-prefetch',
            label: 'Consumer Prefetch',
          },
        ],
      },
      {
        type: 'category',
        label: 'Publishing Messages',
        link: {type: 'doc', id: 'admin-guide'},
        items: [
          {
            type: 'doc',
            id: 'e2e',
            label: 'Exchange to Exchange Bindings',
          },
          {
            type: 'doc',
            id: 'ae',
            label: 'Alternative Exchanges',
          },
          {
            type: 'doc',
            id: 'sender-selected',
            label: 'Sender-selected Distribution',
          },
        ],
      },
      {
        type: 'doc',
        id: 'confirms',
        label: 'Consumer Acknowledgements and Publisher Confirms',
      },
      {
        type: 'category',
        label: 'Working with High Availability Queues and Streams',
        link: {type: 'doc', id: 'admin-guide'},
        items: [
          {
            type: 'doc',
            id: 'queues',
            label: 'Queues in General',
          },
          {
            type: 'doc',
            id: 'quorum-queues',
            label: 'Quorum Queues',
          },
          {
            type: 'doc',
            id: 'classic-queues',
            label: 'Classic Queues',
          },
          {
            type: 'doc',
            id: 'classic-queues',
            label: 'Migrate Mirrored Classic Queues to Quorum Queues',
          },
          {
            type: 'doc',
            id: 'ttl',
            label: 'Queue and Message TTL and the Expiration Feature',
          },
          {
            type: 'doc',
            id: 'maxlength',
            label: 'Set the Queue Length',
          },
          {
            type: 'doc',
            id: 'lazy-queues',
            label: 'Set the Queue Modes: Lazy and Default',
          },
          {
            type: 'doc',
            id: 'dlx',
            label: 'Dead Lettering Feature',
          },
          {
            type: 'doc',
            id: 'priority',
            label: 'Turn your Queues into Priority Queues',
          },
          {
            type: 'doc',
            id: 'streams',
            label: 'Streams',
          },
        ],
      },
      {
        type: 'category',
        label: 'Working with Plugins',
        link: {type: 'doc', id: 'clustering'},
        items: [
          {
            type: 'doc',
            id: 'installing-plugins',
            label: 'Installing Plugins',
          },
          {
            type: 'doc',
            id: 'plugin-development',
            label: 'Plugin Development',
          },
          {
            type: 'category',
            label: 'Management Plugin',
            link: {type: 'doc', id: 'management'},
            items: [
              {
                type: 'doc',
                id: 'management-cli',
                label: 'Management CLI',
              },
            ],
          },
          {
            type: 'category',
            label: 'Federation Plugin',
            link: {type: 'doc', id: 'federation'},
            items: [
              {
                type: 'doc',
                id: 'federated-exchanges',
                label: 'Federated Exchanges',
              },
              {
                type: 'doc',
                id: 'federated-exchanges',
                label: 'Federated Exchanges',
              },
              {
                type: 'doc',
                id: 'federated-queues',
                label: 'Federated Queues',
              },
              {
                type: 'doc',
                id: 'federation-reference',
                label: 'Federation Reference',
              },
            ],
          },
          {
            type: 'category',
            label: 'Shovel Plugin',
            link: {type: 'doc', id: 'shovel'},
            items: [
              {
                type: 'doc',
                id: 'shovel-static',
                label: 'Configuring Static Shovels',
              },
              {
                type: 'doc',
                id: 'shovel-dynamic',
                label: 'Configuring Dynamic Shovels',
              },
            ],
          }, 
          {
            type: 'doc',
            id: 'stream',
            label: 'Stream Plugin',
          },
          {
            type: 'doc',
            id: 'stomp',
            label: 'STOMP Plugin',
          },
          {
            type: 'doc',
            id: 'web-stomp',
            label: 'Web STOMP Plugin',
          },
          {
            type: 'doc',
            id: 'mqtt',
            label: 'MQTT Plugin',
          },
          {
            type: 'doc',
            id: 'web-mqtt',
            label: 'Web MQTT Plugin',
          },
          {
            type: 'doc',
            id: 'ldap',
            label: 'LDAP Plugin',
          },
          {
            type: 'doc',
            id: 'oauth2',
            label: 'OAuth 2.0 Authentication/Authorisation Backend Plugin',
          },    
        ],  
      },
      {
        type: 'doc',
        id: 'distributed',
        label: 'Distributed RabbitMQ Feature',
      },
      {
        type: 'category',
        label: 'Protocols that RabbitMQ Supports',
        link: {type: 'doc', id: 'protocols'},
        items: [
          {
            type: 'link',
            label: 'AMQP 0-9-1 Protocol',
            href: '/tutorials/amqp-concepts'
          },
          {
            type: 'doc',
            id: 'protocol',
            label: 'AMQP 0-9-1 Specification',
          },
          {
            type: 'doc',
            id: 'specification',
            label: 'Differences between AMQP Protocol Versions',
          },
          {
            type: 'doc',
            id: 'channels',
            label: 'Channels',
          },
        ],
      },
      {
        type: 'category',
        label: 'Extensions',
        link: {type: 'doc', id: 'extensions'},
        items: [
          {
            type: 'doc',
            id: 'extensions',
           label: 'Protocol Extensions'
          },
          {
            type: 'doc',
            id: 'direct-reply-to',
            label: 'Direct reply-to',
          },
          {
            type: 'doc',
            id: 'connection-blocked',
            label: 'Blocked Connection Notifications',
          },
          {
            type: 'doc',
            id: 'nack',
            label: 'Negative Acknowledgements',
          },
          {
            type: 'doc',
            id: 'e2e',
            label: 'Exchange to Exchange Bindings',
          },
          {
            type: 'doc',
            id: 'sender-selected',
            label: 'Sender-selected Distribution',
          },
        ],
      }, 
    ],
    },
    


    {
      type: 'category',
      label: 'Configuration and Administration',
      link: {type: 'doc', id: 'configure'},
      items: [
        {
          type: 'doc',
          id: 'relocate',
          label: 'File and Directory Locations',
        },
        {
          type: 'doc',
          id: 'logging',
          label: 'Logging',
        },
        {
          type: 'doc',
          id: 'parameters',
          label: 'Runtime Parameters and Policies',
        },
        {
          type: 'doc',
          id: 'definitions',
          label: 'Schema Definitions',
        },
        {
          type: 'doc',
          id: 'vhosts',
          label: 'Per Virtual Hosts',
        },
        {
          type: 'doc',
          id: 'user-limits',
          label: 'Per User Resource Limits',
        },
        {
          type: 'doc',
          id: 'nettick',
          label: 'Inter-node Connection Heartbeats',
        },
        {
          type: 'doc',
          id: 'runtime',
          label: 'Runtime Tuning',
        },
    
      {
        type: 'category',
        label: 'Authentication and Authorisations',
        link: {type: 'doc', id: 'access-control'},
        items: [
          {
            type: 'doc',
            id: 'authentication',
            label: 'AMQP 0-9-1 Authentication Mechanisms',
          },
          {
            type: 'doc',
            id: 'vhosts',
            label: 'Virtual Hosts',
          },
          {
            type: 'doc',
            id: 'passwords',
            label: 'Credentials and Passwords',
          },
          {
            type: 'doc',
            id: 'oauth2',
            label: 'OAuth 2.0 Support',
          },
          {
            type: 'doc',
            id: 'oauth2-examples',
            label: 'OAuth 2.0 Examples',
          },
          {
            type: 'doc',
            id: 'ldap',
            label: 'LDAP Support',
          },
          {
            type: 'doc',
            id: 'validated-user-id',
            label: 'Validated User-ID',
          },
          {
            type: 'doc',
            id: 'auth-notification',
            label: 'Authentication Failure Notifications',
          },
        ],
      },
      {
        type: 'category',
        label: 'Client Connections, Networking, and TLS',
        link: {type: 'doc', id: 'admin-guide'},
        items: [
          {
            type: 'doc',
            id: 'networking',
            label: 'Networking',
          },
          {
            type: 'doc',
            id: 'troubleshooting-networking',
            label: 'Troubleshooting Network Connectivity',
          },
          {
            type: 'doc',
            id: 'ssl',
            label: 'TLS Support',
          },
          {
            type: 'doc',
            id: 'clustering-ssl',
            label: 'Using TLS for Inter-node Traffic',
          },
          {
            type: 'doc',
            id: 'troubleshooting-ssl',
            label: 'Troubleshooting TLS Support',
          },
        ],
      },
      {
        type: 'category',
        label: 'Monitoring and Auditing',
        link: {type: 'doc', id: 'monitoring'},
        items: [
          {
            type: 'doc',
            id: 'prometheus',
            label: 'Monitoring with Prometheus and Grafana',
          },
          {
            type: 'doc',
            id: 'management',
            label: 'Monitoring with the Management Plugin',
          },
          {
            type: 'doc',
            id: 'event-exchange',
            label: 'Using the Event Exchange Plugin to Monitor Events',
          },
          {
            type: 'doc',
            id: 'firehose',
            label: 'Message Tracing',
          },
          {
            type: 'doc',
            id: 'amqp-wireshark',
            label: 'Inspecting AMQP Traffic with Wireshark',
          },
          {
            type: 'doc',
            id: 'heartbeats',
            label: 'Detecting Dead TCP Connections with Heartbeats and TCP Keepalives',
          },
        ],
      },
      {
        type: 'category',
        label: 'Resource Management',
        link: {type: 'doc', id: 'clustering'},
        items: [
          {
            type: 'doc',
            id: 'memory-use',
            label: 'Analyzing how Memory is Used',
          },
          {
            type: 'doc',
            id: 'alarms',
            label: 'Memory and Disk Alarms',
          },
          {
            type: 'doc',
            id: 'disk-alarms',
            label: 'Free Disk Space Alarms',
          },
          {
            type: 'doc',
            id: 'flow-control',
            label: 'Flow Control',
          },
        ],  
      },
      {
        type: 'doc',
        id: 'backup',
        label: 'Backup and Restore',
      },
      {
        type: 'category',
        label: 'Protocols that RabbitMQ Supports',
        link: {type: 'doc', id: 'protocols'},
        items: [
          {
            type: 'link',
            label: 'AMQP 0-9-1 Protocol',
            href: '/tutorials/amqp-concepts'
          },
          {
            type: 'doc',
            id: 'protocol',
            label: 'AMQP 0-9-1 Specification',
          },
          {
            type: 'doc',
            id: 'specification',
            label: 'Differences between AMQP Protocol Versions',
          },
          {
            type: 'doc',
            id: 'channels',
            label: 'Channels',
          },
        ],
      },
      {
        type: 'category',
        label: 'Extensions',
        link: {type: 'doc', id: 'extensions'},
        items: [
          {
            type: 'doc',
            id: 'extensions',
           label: 'Protocol Extensions'
          },
          {
            type: 'doc',
            id: 'direct-reply-to',
            label: 'Direct reply-to',
          },
          {
            type: 'doc',
            id: 'connection-blocked',
            label: 'Blocked Connection Notifications',
          },
          {
            type: 'doc',
            id: 'nack',
            label: 'Negative Acknowledgements',
          },
          {
            type: 'doc',
            id: 'e2e',
            label: 'Exchange to Exchange Bindings',
          },
          {
            type: 'doc',
            id: 'sender-selected',
            label: 'Sender-selected Distribution',
          },
          {
            type: 'link',
            label: 'Integrating with Client Libraries',
            href: '/integrate-withclientlib'
          },
        ],
      }, 
    ],
    },
    
  
//PAULA EXISTING 
    {
      type: 'category',
      label: 'Client Documentation',
      link: {type: 'doc', id: 'clients'},
      items: [
        {
          type: 'category',
          label: 'Java Client Guide',
          link: {type: 'doc', id: 'api-guide'},
          items: [
            {
              type: 'doc',
              id: 'java-tools',
              label: 'Java Client Tools',
            },
          ],
        },
        {
          type: 'category',
          label: 'JMS Client',
          link: {type: 'doc', id: 'jms-client'},
          items: [
            {
              type: 'link',
              label: 'JMS Client Spec Compliance',
              href: 'https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/jms-client-compliance.md',
            },
          ],
        },
        {
          type: 'doc',
          id: 'dotnet-api-guide',
          label: '.NET Client Guide',
        },
        {
          type: 'doc',
          id: 'erlang-client-user-guide',
          label: 'Erlang Client Guide',
        },
        {
          type: 'doc',
          id: 'heartbeats',
          label: 'Heartbeats',
        },
        {
          type: 'doc',
          id: 'amqp-0-9-1-reference',
          label: 'AMQP 0-9-1 Reference',
        },
        {
          type: 'doc',
          id: 'uri-spec',
          label: 'AMQP 0-9-1 URI Spec',
        },
      ]
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {type: 'doc', id: 'plugins'},
      items: [
        {
          type: 'doc',
          id: 'management',
          label: 'Management plugin',
        },
        {
          type: 'category',
          label: 'Federation plugin',
          link: {type: 'doc', id: 'federation'},
          items: [
            {
              type: 'doc',
              id: 'federated-exchanges',
              label: 'Exchanges',
            },
            {
              type: 'doc',
              id: 'federated-queues',
              label: 'Queues',
            },
            {
              type: 'doc',
              id: 'federation-reference',
              label: 'Reference',
            },
          ],
        },
        {
          type: 'category',
          label: 'Shovel plugin',
          link: {type: 'doc', id: 'shovel'},
          items: [
            {
              type: 'doc',
              id: 'shovel-static',
              label: 'Static Shovels',
            },
            {
              type: 'doc',
              id: 'shovel-dynamic',
              label: 'Dynamic Shovels',
            },
          ],
        },
        'stream',
        'stomp',
        {
          type: 'doc',
          id: 'web-stomp',
          label: 'STOMP-over-WebSockets',
        },
        'mqtt',
        {
          type: 'doc',
          id: 'web-mqtt',
          label: 'MQTT-over-WebSockets',
        },
        {
          type: 'doc',
          id: 'ldap',
          label: 'LDAP',
        },
        {
          type: 'doc',
          id: 'oauth2',
          label: 'OAuth 2.0 plugin',
        },
        {
          type: 'doc',
          id: 'installing-plugins',
          label: 'Installing Plugins',
        },
        {
          type: 'doc',
          id: 'plugin-development',
          label: 'Plugin Development',
        },
      ]
    },
    {
      type: 'category',
      label: 'Protocol',
      link: {type: 'doc', id: 'protocol'},
      items: [
        {
          type: 'doc',
          id: 'specification',
          label: 'Compatibility',
        },
        'interoperability',
        'semantics',
        {
          type: 'doc',
          id: 'amqp-0-9-1-quickref',
          label: 'Quick Reference',
        },
        {
          type: 'doc',
          id: 'amqp-0-9-1-reference',
          label: 'Full Reference',
        },
        {
          type: 'doc',
          id: 'amqp-0-8-to-0-9-1',
          label: 'Differences from AMQP 0-8 to 0-9-1',
        },
        {
          type: 'doc',
          id: 'amqp-wireshark',
          label: 'Traffic Analyzer',
        },
      ]
    },
    {
      type: 'category',
      label: 'Our Extensions',
      link: {type: 'doc', id: 'extensions'},
      items: [
        {
          type: 'doc',
          id: 'confirms',
          label: 'Confirms',
        },
        'consumer-cancel',
        'consumer-prefetch',
        'consumer-priority',
        'direct-reply-to',
        {
          type: 'doc',
          id: 'connection-blocked',
          label: 'Blocked Connections',
        },
        {
          type: 'doc',
          id: 'nack',
          label: 'basic.nack',
        },
        {
          type: 'doc',
          id: 'e2e',
          label: 'e2e Bindings',
        },
        {
          type: 'doc',
          id: 'ae',
          label: 'Alternate Exchanges',
        },
        {
          type: 'doc',
          id: 'sender-selected',
          label: 'Sender Routing',
        },
        {
          type: 'doc',
          id: 'ttl',
          label: 'TTL',
        },
        {
          type: 'doc',
          id: 'dlx',
          label: 'Dead Lettering',
        },
        {
          type: 'doc',
          id: 'maxlength',
          label: 'Length Limit',
        },
        {
          type: 'doc',
          id: 'priority',
          label: 'Priority Queues',
        },
        'validated-user-id',
        {
          type: 'doc',
          id: 'auth-notification',
          label: 'Auth Failure',
        },
        'spec-differences',
      ]
    },
    {
      type: 'category',
      label: 'Building',
      link: {type: 'doc', id: 'build'},
      items: [
        {
          type: 'doc',
          id: 'build-server',
          label: 'Build the Server',
        },
        {
          type: 'doc',
          id: 'build-java-client',
          label: 'Build the Java Client',
        },
        {
          type: 'doc',
          id: 'build-dotnet-client',
          label: 'Build the .NET Client',
        },
        {
          type: 'doc',
          id: 'build-erlang-client',
          label: 'Build the Erlang Client',
        },
        {
          type: 'doc',
          id: 'github',
          label: 'Our use of Git and GitHub',
        },
      ]
    },
    'previous',
    {
      type: 'doc',
      id: 'mpl',
      label: 'License',
    },
      ],
};

export default sidebars;
